# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('assets', 'assets'),
    ],
    hiddenimports=[
        'paho',
        'paho.mqtt',
        'paho.mqtt.client',
        'network',
        'network.mqtt_manager',
        'network.config_manager',
        'network.updater',
        'ui',
        'ui.theme',
        'ui.welcome_screen',
        'ui.host_view',
        'ui.participant_view',
        'ui.main_window',
        'tkinter',
        'tkinter.ttk',
        'tkinter.messagebox',
        'urllib.request',
        'json',
        'winsound',
        'threading',
        'subprocess',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'torch',
        'torchvision',
        'ultralytics',
        'matplotlib',
        'scipy',
        'cv2',
        'polars',
        'google',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='StreamerPartyReady',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='assets/icon.ico',
)
